"""The vendored artifact must still be the bytes core shipped.

`reference/rederivable-manifest/` is core's receipt artifact, pinned at v3. Its
manifests are content-addressed: `validate.py --verify` recomputes four SHA-256
digests and re-derives the verdict from the archived evidence, so any change to
the bytes -- one byte -- makes it fail.

That is a good property and a sharp edge. The bytes are not protected by anything
the language can see: no import reaches them, no type describes them. The realistic
way to break them is not a bad edit but an *encoding* one -- git's Windows default
(`core.autocrlf=true`) rewriting LF to CRLF on checkout. `.gitattributes` prevents
that, but `.gitattributes` is configuration, and configuration that nothing checks
is configuration that silently stops being true.

So this asserts the outcome rather than the mechanism: the vendored bytes carry no
CR, the artifact self-tests clean, and every shipped manifest still verifies. A
future `.gitattributes` edit, a stray normalising filter, or a well-meaning
reformat all surface here instead of surfacing as `e_digest mismatch: archived
evidence differs from frozen evidence` -- which reads as evidence tampering and is
the worst way for an encoding bug to present itself in a forensics tool.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

ARTIFACT = Path(__file__).resolve().parents[2] / "reference" / "rederivable-manifest"
MANIFESTS = sorted((ARTIFACT / "manifests").glob("*.json"))
# __pycache__ is generated by running validate.py; it is not vendored.
VENDORED = sorted(p for p in ARTIFACT.rglob("*") if p.is_file() and "__pycache__" not in p.parts)


def _run(*args: str) -> subprocess.CompletedProcess[str]:
    """Run validate.py from inside the artifact: it imports `canonical` flat."""
    return subprocess.run(
        [sys.executable, "validate.py", *args],
        cwd=ARTIFACT,
        capture_output=True,
        text=True,
        check=False,
    )


def test_artifact_is_present() -> None:
    """A missing artifact must fail loudly, not vacuously pass the tests below."""
    assert ARTIFACT.is_dir(), f"vendored artifact missing at {ARTIFACT}"
    assert len(MANIFESTS) == 3, f"expected 3 shipped manifests, found {len(MANIFESTS)}"


@pytest.mark.parametrize("path", VENDORED, ids=lambda p: p.name)
def test_vendored_bytes_carry_no_carriage_return(path: Path) -> None:
    """The exact corruption core.autocrlf=true inflicts, caught at the byte level."""
    assert b"\r" not in path.read_bytes(), (
        f"{path.relative_to(ARTIFACT)} contains CR. Line endings have been rewritten "
        f"-- check .gitattributes and core.autocrlf. The pinned digests will not "
        f"reproduce until the bytes are restored."
    )


def test_artifact_selftest_passes() -> None:
    result = _run("--selftest")
    assert result.returncode == 0, f"artifact self-test failed:\n{result.stdout}\n{result.stderr}"
    assert "ALL PASS" in result.stdout


@pytest.mark.parametrize("manifest", MANIFESTS, ids=lambda p: p.stem[:12])
def test_shipped_manifest_verifies(manifest: Path) -> None:
    result = _run("--verify", str(manifest.relative_to(ARTIFACT)))
    assert result.returncode == 0, f"{manifest.name} failed to verify:\n{result.stdout}"
    assert "VERIFIED" in result.stdout
