"""Received bytes are frozen verbatim; generated bytes are canonical (W7, E10/R004).

The two disciplines are not symmetric, and the asymmetry is the point:

* **Received** data records what the enforcement point *sent*. `250.00` stays
  `250.00`. Canonicalising it would replace the caller's bytes with this PDP's, and
  the evidence would then attest something nobody transmitted.
* **Generated** data -- the budget object, the receipt envelope -- is canonicalised,
  because there are no sender's bytes to preserve and one form is what makes a
  digest reproducible.

Which discipline produced a row is itself evidence, so it is recorded rather than
inferred (`params_provenance`). A row that says `received` can be re-derived against
what the caller transmitted; one that says `serialized` can only be re-derived
against what this PDP would produce. Collapsing them lets the second pass for the
first, which is why the column exists and why NULL means *unknown* rather than
either value.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest

from onedoor.guardrail import audit, policy_loader
from onedoor.guardrail.decision import decide_and_reserve
from onedoor.guardrail.executor import EngineConfig
from onedoor.guardrail.models import ActionRequest, Bounds, Policy, Source, Tier
from onedoor.guardrail.received import Provenance, extract_raw_member
from onedoor.store.db import Database

NOW = datetime(2026, 7, 5, 12, 0, tzinfo=UTC)
CONFIG = EngineConfig(approval_ttl_seconds=3600, connector_timeout_seconds=5.0, tz=ZoneInfo("UTC"))


@pytest.fixture
def db(tmp_path: Path) -> Database:
    database = Database(str(tmp_path / "freeze.db"))
    database.init()
    conn = database.connect()
    policy_loader.upsert(
        conn,
        Policy(
            action_type="demo.note",
            tier=Tier.AUTO,
            dry_run=False,
            compensating_command="demo.note",
            bounds=Bounds(strict_params=False),
        ),
    )
    conn.close()
    return database


def _decide(conn: object, params: dict, raw: str | None) -> None:
    decide_and_reserve(
        ActionRequest(
            request_id=uuid4(),
            action_type="demo.note",
            params=params,  # type: ignore[arg-type]
            params_raw=raw,
            source=Source.LLM,
            rationale="freeze",
            created_at=NOW,
        ),
        conn=conn,  # type: ignore[arg-type]
        config=CONFIG,
        now=NOW,
    )


def _row(conn: object) -> dict:
    r = conn.execute(  # type: ignore[attr-defined]
        "SELECT params_json, params_provenance FROM actions_audit ORDER BY id DESC LIMIT 1"
    ).fetchone()
    return dict(r)


def test_received_bytes_are_stored_exactly_as_sent(db: Database) -> None:
    """Not parsed, not re-serialized, not canonicalised."""
    conn = db.connect()
    try:
        sent = '{"amount":250.00,"note":"kept  as   sent"}'
        _decide(conn, {"amount": Decimal("250.00"), "note": "kept  as   sent"}, sent)
        row = _row(conn)
        assert row["params_json"] == sent, "the stored bytes must be the received bytes"
        assert row["params_provenance"] == Provenance.RECEIVED.value
    finally:
        conn.close()


def test_canonicalising_received_bytes_would_change_them(db: Database) -> None:
    """The negative control: without the freeze, this row would differ.

    If `250.00` came back as `250`, the freeze is not happening -- the record would be
    showing what this PDP writes rather than what the caller sent.
    """
    conn = db.connect()
    try:
        sent = '{"amount":250.00}'
        canonical = audit.dumps_json_value({"amount": Decimal("250.00")})
        assert canonical != sent, "the probe is pointless unless the two forms differ"
        _decide(conn, {"amount": Decimal("250.00")}, sent)
        assert _row(conn)["params_json"] == sent
    finally:
        conn.close()


def test_the_in_process_binding_says_serialized_not_received(db: Database) -> None:
    """No bytes were received, so none are claimed."""
    conn = db.connect()
    try:
        _decide(conn, {"amount": Decimal("250.00")}, None)
        row = _row(conn)
        assert row["params_provenance"] == Provenance.SERIALIZED.value
        assert row["params_json"] == audit.dumps_json_value({"amount": Decimal("250.00")})
    finally:
        conn.close()


def test_provenance_is_never_derived_from_the_params(db: Database) -> None:
    """A reconstructed value would be a PDP serialization wearing the label 'received'.

    Two requests with identical `params` but different provenance must differ in the
    row, because the difference is real: one is the caller's bytes and one is ours.
    """
    conn = db.connect()
    try:
        params = {"amount": Decimal("250.00")}
        _decide(conn, params, '{"amount":250.00}')
        received = _row(conn)
        _decide(conn, params, None)
        serialized = _row(conn)
        assert received["params_provenance"] != serialized["params_provenance"]
        assert received["params_json"] != serialized["params_json"]
    finally:
        conn.close()


def test_the_digest_is_derivable_so_no_digest_column_is_needed(db: Database) -> None:
    """R004 dissolved `received_digest`: the bytes are stored, so hash them.

    A stored digest beside stored bytes is a second answer to a question the bytes
    already answer (X-14) -- and the one that can drift.
    """
    import hashlib

    conn = db.connect()
    try:
        sent = '{"amount":250.00}'
        _decide(conn, {"amount": Decimal("250.00")}, sent)
        stored = _row(conn)["params_json"]
        assert (
            hashlib.sha256(stored.encode("utf-8")).hexdigest()
            == hashlib.sha256(sent.encode("utf-8")).hexdigest()
        )
        cols = {r[1] for r in conn.execute("PRAGMA table_info(actions_audit)")}
        assert "received_digest" not in cols
    finally:
        conn.close()


@pytest.mark.parametrize(
    ("document", "expected"),
    [
        ('{"params":{"a":1}}', '{"a":1}'),
        ('{"x":0,"params":[1,2],"y":3}', "[1,2]"),
        # braces and escaped quotes inside a string must not cut the value short
        (r'{"params":{"s":"}{ \"q\" "},"z":1}', r'{"s":"}{ \"q\" "}'),
        # a nested key of the same name must not win over the top-level one
        ('{"outer":{"params":"no"},"params":{"yes":1}}', '{"yes":1}'),
        ('{"nope":1}', None),
        ("not json at all", None),
        ("[1,2,3]", None),  # not an object
    ],
)
def test_the_extractor_returns_exact_source_text_or_nothing(
    document: str, expected: str | None
) -> None:
    """An approximate answer would be recorded as *verbatim*, so there isn't one.

    Deliberately not a regex: JSON strings can contain braces, quotes and escapes, so
    a scanner that does not actually parse will eventually cut a value in half and
    store the half as evidence.
    """
    assert extract_raw_member(document, "params") == expected


def test_an_old_row_has_unknown_provenance_not_an_assumed_one(db: Database) -> None:
    """NULL means unknown. Rows written before 0.4.0 were neither verbatim nor canonical.

    Inferring either value for them would be inventing evidence: under the old round
    trip the bytes were `json.dumps(..., default=str)` output, which is neither what
    the caller sent nor a canonical form.
    """
    conn = db.connect()
    try:
        conn.execute(
            "INSERT INTO actions_audit (request_id, kind, action_type, source, params_json,"
            " decision, reason_code, nominal_tier, effective_tier, created_at)"
            " VALUES ('old','decision','demo.note','llm','{}','denied','bounds',1,1,?)",
            (NOW.isoformat(),),
        )
        row = conn.execute(
            "SELECT params_provenance FROM actions_audit WHERE request_id='old'"
        ).fetchone()
        assert row["params_provenance"] is None
    finally:
        conn.close()


def test_generated_structures_are_still_canonical_not_verbatim() -> None:
    """The other half of E10: the budget object is ours, so it is canonicalised.

    Received data is frozen; generated data is normalised. Applying the freeze to a
    structure this PDP produced would make its digest depend on how it happened to be
    built rather than on what it means.
    """
    from onedoor.guardrail.models import Budget

    budget = Budget(
        dimension="value",
        unit="EUR",
        window="day",
        limit="250",
        consumed="250",
        remaining="0",
        window_resets_at="2026-07-06T00:00:00Z",
    )
    rendered = audit.dumps_json_value(budget.model_dump())
    assert json.loads(rendered)["limit"] == "250"
    assert list(json.loads(rendered)) == sorted(json.loads(rendered)), "canonical: keys sorted"
