"""A chain written by the real `/2`-era code, kept on disk as evidence.

`tests/fixtures/chain_v2_61aaeed.db` is not generated by this test suite. It was
built once, by checking out `61aaeed` (the accepted commit -- the last one
before the `/3` bump) into a separate worktree and running its own
`decide_and_reserve`/`chain.enable` against a fresh database: 5 rows, one policy
(`demo.v2chain`, Tier 2 with daily-rate and euro caps), chaining enabled from
genesis. Committed as evidence that the CURRENT code (post-`/3`) still verifies
rows the OLD code actually sealed -- a regenerated fixture cannot show that,
because it would be written by the new code testing itself.

A copy is used everywhere a test needs to mutate anything (SQLite locks, and the
committed file is evidence, not a scratch pad); read-only checks may open it
directly.
"""

from __future__ import annotations

import shutil
from decimal import Decimal
from pathlib import Path
from uuid import uuid4
from zoneinfo import ZoneInfo

from onedoor.guardrail import chain
from onedoor.guardrail.decision import PermittedIntent, decide_and_reserve
from onedoor.guardrail.executor import EngineConfig
from onedoor.guardrail.models import ActionRequest, Source
from onedoor.guardrail.preimage import VERSION_2, VERSION_3
from onedoor.store.db import Database
from tests.conftest import FROZEN_NOW

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "chain_v2_61aaeed.db"


def _copy(tmp_path: Path) -> Database:
    target = tmp_path / "chain_v2_copy.db"
    shutil.copy(FIXTURE, target)
    return Database(str(target))


def test_the_stored_2_chain_verifies_unchanged_under_the_current_code(
    tmp_path: Path,
) -> None:
    """The exact claim this fixture exists to check: rows sealed by the OLD /2 code, on
    disk, unmodified, still verify under the code as it stands at 8ac78aa+."""
    conn = _copy(tmp_path).connect()
    try:
        report = chain.verify_chain(conn)
        assert report.sound, (
            f"a stored /2 chain FAILED to verify under the current code: "
            f"{[(r.status.value, r.detail) for r in report.regions]}"
        )
        assert report.chained_rows == 5, "the fixture's own row count"
        versions = {
            r["preimage_version"]
            for r in conn.execute(
                "SELECT preimage_version FROM actions_audit WHERE seq IS NOT NULL"
            )
        }
        assert versions == {VERSION_2}, "every row in this fixture must actually be /2"
    finally:
        conn.close()


def test_the_stored_chain_continues_into_3_and_the_mixed_chain_verifies(
    tmp_path: Path,
) -> None:
    """Not simulated: the fixture's real /2 rows, followed by REAL /3 rows written
    by decide_and_reserve as it stands today (CURRENT_VERSION == VERSION_3)."""
    database = _copy(tmp_path)
    conn = database.connect()
    try:
        config = EngineConfig(
            approval_ttl_seconds=3600, connector_timeout_seconds=5.0, tz=ZoneInfo("UTC")
        )
        for i in range(3):
            request = ActionRequest(
                request_id=uuid4(),
                action_type="demo.v2chain",
                params={"amount_eur": Decimal(f"{i + 10}.00")},
                source=Source.LLM,
                rationale="mixed-chain continuation row",
                cost_eur=Decimal(f"{i + 10}.00"),
                created_at=FROZEN_NOW,
            )
            outcome = decide_and_reserve(request, conn=conn, config=config, now=FROZEN_NOW)
            assert isinstance(outcome, PermittedIntent)

        report = chain.verify_chain(conn)
        assert report.sound, (
            f"the mixed /2 -> /3 chain did not verify: "
            f"{[(r.status.value, r.detail) for r in report.regions]}"
        )
        assert report.chained_rows == 5 + 3
        versions = {
            r["preimage_version"]
            for r in conn.execute(
                "SELECT preimage_version FROM actions_audit WHERE seq IS NOT NULL"
            )
        }
        assert versions == {VERSION_2, VERSION_3}, "the fixture must actually span both versions"
    finally:
        conn.close()
