"""Shipped policy packs (ND-052 / S5).

**A pack ships policy**, so every law binding policy binds it — and a pack is the first
artifact that would carry such a defect *at scale*, because one bad template becomes one
bad rule in every deployment that adopts it. Its own tests assert those laws through the
engine's own checkers rather than assuming them.

Why the packs live **inside** the package
-------------------------------------------
Measured, not assumed: `pyproject.toml` sets `include = ["onedoor*"]`, and the `0.5.0`
wheel contains no `config/policies.yaml`. **A repo directory does not travel in a wheel**
— the lesson `0.3.0` paid for by shipping a wheel with no migrations. So packs sit here,
beside `store/migrations/` and `viewer/_vendor/`, and
`tests/templates/test_pack_ships.py` asserts they are in the built artifact.

Two identities, each answering exactly one question
-----------------------------------------------------
**`PACK_DIGEST` is the file identity** — *is this byte-for-byte the pack that shipped?*
It covers every file in the pack, comments included, because S6 will record the pack as
part of its **instrument** and a proposer's output depends on the exact bytes it read.
Generated by `python -m scripts.pack_digest`, never typed (X-11).

**The meaning identity already exists and is cited, never re-minted.** It is
`backtest.policy_digest` over the pack's models — the same value S1 computes and S2's
ceremony records as `candidate_digest`. A second field carrying it would be R040's
second-address problem wearing a new name, so `Pack.policy_digest()` calls that function
rather than reproducing it.
"""

from __future__ import annotations

import hashlib
import sqlite3
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from onedoor.guardrail.models import Caps, EffectPolicy, Policy

if TYPE_CHECKING:  # pragma: no cover - import cycle at runtime, not at type time
    from onedoor.studio.ratify import Ratification

TEMPLATES_DIR = Path(__file__).parent

PACK_FILES = ("policies.yaml", "PACK.md")
"""Every file the digest covers, declared rather than globbed.

A glob would silently change the pack's identity when an editor dropped a stray file
beside it, and an identity that moves for reasons nobody chose is not an identity.
"""


def _pack_digest(directory: Path) -> str:
    """SHA-256 over the pack's files: for each, its name, its length, then its bytes.

    Length-prefixed and name-prefixed so no two different packs can share a preimage by
    rearranging where one file ends and the next begins — the same reasoning that puts
    a length in front of every field in the row preimage.

    Bytes, not parsed content: this answers *did these exact files ship*, comments and
    all, because that is what an instrument record has to pin.
    """
    digest = hashlib.sha256()
    for name in PACK_FILES:
        raw = (directory / name).read_bytes()
        digest.update(name.encode("utf-8"))
        digest.update(len(raw).to_bytes(8, "big"))
        digest.update(raw)
    return digest.hexdigest()


@dataclass(frozen=True)
class Pack:
    """A shipped policy pack: its files, its identity, and how it is adopted."""

    name: str
    directory: Path

    @property
    def policies_path(self) -> Path:
        return self.directory / "policies.yaml"

    @property
    def boundary_path(self) -> Path:
        return self.directory / "PACK.md"

    def file_digest(self) -> str:
        """The pack's **file** identity, computed from what is on disk right now."""
        return _pack_digest(self.directory)

    def load(self) -> tuple[list[Policy], list[EffectPolicy]]:
        """The pack's models. Parsed by the loader's own reader, never a second one.

        `policy_loader._safe_load_decimal` is what reads policy YAML for the engine —
        including its rule that a number is a `Decimal` and that NaN/Infinity are
        malformed. A pack read by a different parser would be a pack whose meaning
        differs from what the engine will enforce.
        """
        from onedoor.guardrail import policy_loader

        raw = policy_loader._safe_load_decimal(self.policies_path.read_text(encoding="utf-8"))
        policies = [Policy.model_validate(entry) for entry in raw.get("policies", [])]
        effects = [
            EffectPolicy(
                effect=name,
                min_tier=cfg["min_tier"] if cfg.get("min_tier") is not None else None,
                # Validated through the model rather than passed as a bare dict: a cap
                # that fails validation must fail HERE, where the pack is read, not
                # later where the error names a decision instead of a template.
                caps=Caps.model_validate(cfg.get("caps", {}) or {}),
            )
            for name, cfg in (raw.get("effects", {}) or {}).items()
        ]
        return policies, effects

    def policy_digest(self) -> str:
        """The pack's **meaning** identity — cited, never re-minted.

        This is `backtest.policy_digest`, the function S1 built and S2's ceremony
        records as `candidate_digest`. Calling it rather than reproducing it is what
        makes `adopt`'s receipt recomputable by anyone holding the pack.
        """
        from onedoor.studio import backtest

        policies, _ = self.load()
        return backtest.policy_digest(policies)

    def adopt(
        self,
        conn: sqlite3.Connection,
        *,
        ratified_by_session: str,
        now: datetime,
        backtest_digest: str | None = None,
    ) -> Ratification:
        """Adopt the pack **through the ratification ceremony** (R051 §6).

        Loading a pack changes the rules the engine enforces, which is precisely the act
        S2 built a ceremony and a receipt for. The alternative — a plain `load_file`
        upsert — would make a pack the one policy change in this product that leaves no
        trace.

        No schema change was needed for lineage: the receipt's `candidate_digest` **is**
        this pack's `policy_digest()` by construction, so pack provenance is recoverable
        by **recomputation** rather than by a stored pointer.
        """
        from onedoor.guardrail import policy_loader
        from onedoor.studio import ratify

        policies, effects = self.load()
        return ratify.ratify(
            conn,
            policies,
            effects=effects,
            expected_version=policy_loader.current_version(conn),
            ratified_by_session=ratified_by_session,
            backtest_digest=backtest_digest,
            now=now,
        )


PAYMENTS = Pack(name="payments", directory=TEMPLATES_DIR / "payments")
"""Worked examples: payments. **Not a compliance artifact** — see its `PACK.md`, which
names sanctions screening, KYC, chargebacks, multi-currency settlement and regulatory
reporting as absent, by name rather than by disclaimer."""

PACKS = (PAYMENTS,)

PACK_DIGEST = "0327292ab66088147d6e829bd2479f4f27681dca9ecdafceebf7d320b9146c9f"
"""File identity of `PAYMENTS`, GENERATED BY TOOLING AND NEVER TYPED (X-11).

Regenerate with `python -m scripts.pack_digest --write`. If it disagrees with the files,
`tests/templates/test_pack_identity.py` fails and someone has to look at what changed
rather than absorbing it — the `SPEC_DIGEST` pattern, for the same reason: a shipped
artifact that drifts quietly is the failure mode this whole product exists to prevent.
"""
