"""The payments pack (ND-052 / S5, T1–T6).

R051 §7's expected standing lives here. Three groups:

**The law family**, asserted through the engine's own checkers and never through a
re-implementation of them — `validate_policy` refuses, `coverage.build` maps, and this
suite reads their answers. A checker written for the pack would eventually disagree with
the engine, in the direction that lets a bad template through.

**The behaviour**, asserted as **verdicts** rather than as non-errors. A test that only
says "it loaded" documents nothing about an artifact whose whole purpose is that someone
trusts it without reading it.

**The boundary**, asserted as *named* absences. A named gap is a service to the reader; a
disclaimer is a service to the writer.
"""

from __future__ import annotations

import zipfile
from decimal import Decimal
from pathlib import Path
from sqlite3 import Connection

import pytest

from onedoor.guardrail import policy_loader
from onedoor.guardrail.decision import PermittedIntent, decide_and_reserve
from onedoor.guardrail.executor import EngineConfig
from onedoor.guardrail.models import Tier
from onedoor.studio import backtest, coverage, ratify
from onedoor.templates import PACK_DIGEST, PACK_FILES, PACKS, PAYMENTS
from tests.conftest import FROZEN_NOW, make_request

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def adopted(fresh: Connection) -> Connection:
    """A store with the pack in force, adopted the documented way — via the ceremony."""
    PAYMENTS.adopt(fresh, ratified_by_session="tests", now=FROZEN_NOW)
    return fresh


def _decide(conn: Connection, config: EngineConfig, action: str, params: dict, cost="0"):
    return decide_and_reserve(
        make_request(action, params, cost_eur=Decimal(cost)),
        conn=conn,
        config=config,
        now=FROZEN_NOW,
    )


def _verdict(outcome) -> tuple[str, int]:
    if isinstance(outcome, PermittedIntent):
        return "permitted", int(outcome.effective_tier)
    return outcome.decision.decision.value, int(outcome.decision.effective_tier)


# --- T1: it ships ------------------------------------------------------------------


def test_the_pack_is_in_the_built_wheel() -> None:
    """A repo directory does not travel in a wheel — the `0.3.0` class.

    Skipped rather than silently passing when no wheel has been built: *absent* is not
    *verified*, and a test that quietly passes with nothing to look at is the failure
    this project keeps paying for.
    """
    wheels = sorted((ROOT / "dist").glob("*.whl"))
    if not wheels:
        pytest.skip("no wheel built; run `python -m build` to check packaging")
    names = set(zipfile.ZipFile(wheels[-1]).namelist())
    for filename in PACK_FILES:
        assert f"onedoor/templates/payments/{filename}" in names, (
            f"{filename} is missing from {wheels[-1].name} — the pack would not reach an "
            "installed onedoor at all"
        )


def test_every_declared_pack_file_exists() -> None:
    for pack in PACKS:
        for filename in PACK_FILES:
            assert (pack.directory / filename).is_file(), f"{pack.name}/{filename} missing"


# --- T4: the two identities ---------------------------------------------------------


def test_the_committed_pack_digest_matches_the_files() -> None:
    """Generated by tooling and never typed. Regenerate with `python -m scripts.pack_digest`."""
    assert PAYMENTS.file_digest() == PACK_DIGEST, (
        "PACK_DIGEST has drifted from the pack's files. Look at what changed, then "
        "`python -m scripts.pack_digest --write`."
    )


def test_the_file_digest_changes_when_a_comment_changes(tmp_path: Path) -> None:
    """It is the INSTRUMENT identity, so comments count — S6's output depends on them."""
    from onedoor.templates import Pack

    copy = tmp_path / "payments"
    copy.mkdir()
    for filename in PACK_FILES:
        (copy / filename).write_bytes((PAYMENTS.directory / filename).read_bytes())
    twin = Pack(name="payments", directory=copy)
    assert twin.file_digest() == PACK_DIGEST

    policies = copy / "policies.yaml"
    policies.write_bytes(b"# a new comment\n" + policies.read_bytes())
    assert twin.file_digest() != PACK_DIGEST


def test_the_meaning_digest_is_cited_and_not_re_minted() -> None:
    """`policy_digest` is S1's function, called — not a second implementation of it."""
    policies, _ = PAYMENTS.load()
    assert PAYMENTS.policy_digest() == backtest.policy_digest(policies)


def test_a_comment_change_does_not_move_the_meaning_digest(tmp_path: Path) -> None:
    """The two identities answer different questions, which is why there are two."""
    from onedoor.templates import Pack

    copy = tmp_path / "payments"
    copy.mkdir()
    for filename in PACK_FILES:
        (copy / filename).write_bytes((PAYMENTS.directory / filename).read_bytes())
    policies = copy / "policies.yaml"
    policies.write_bytes(b"# a new comment\n" + policies.read_bytes())
    twin = Pack(name="payments", directory=copy)

    assert twin.file_digest() != PAYMENTS.file_digest(), "file identity must move"
    assert twin.policy_digest() == PAYMENTS.policy_digest(), "meaning identity must not"


# --- T2 + T3: the law family, through the engine's own checkers --------------------


PLACEHOLDERS = ("{{", "}}", "<FILL", "TODO", "XXX", "CHANGEME")


def value_positions(yaml_text: str) -> list[str]:
    """Every line's content with its comment stripped — where a placeholder would be a hole.

    Comment-stripped on purpose, and the reason is a law rather than a convenience. The
    first version of this check scanned the whole file and fired on the pack's own
    comment *explaining* that `{{daily_cap}}` is forbidden — a check outrunning its name,
    which is a false alarm. R050's deciding principle: **narrow the check to what it
    always claimed; never degrade the artifact to satisfy the check.** Deleting the
    explanation from the pack to appease this test would have let a guard erode the thing
    it guards.
    """
    out = []
    for line in yaml_text.splitlines():
        stripped = line.split("#", 1)[0]
        if stripped.strip():
            out.append(stripped)
    return out


@pytest.mark.parametrize(
    "line",
    ["      eur_day: {{daily_cap}}", "    tier: <FILL IN>", "  cost_param: TODO"],
)
def test_a_placeholder_in_a_value_is_caught(line: str) -> None:
    """The guard keeps its teeth: narrowing must not defang it."""
    assert any(marker in v for v in value_positions(line) for marker in PLACEHOLDERS)


@pytest.mark.parametrize(
    "line",
    [
        "# `{{daily_cap}}` is not a Policy, so nothing can check it",
        "  eur_day: 500.00  # never write {{...}} here",
        "# TODO items belong in the backlog, not in a pack",
    ],
)
def test_a_placeholder_named_in_a_comment_is_not_a_hole(line: str) -> None:
    """The other direction, which is the false alarm this narrowing fixed."""
    assert not any(marker in v for v in value_positions(line) for marker in PLACEHOLDERS)


def test_the_pack_contains_no_placeholders() -> None:
    """*A blank is a promise that someone will remember.*

    And the half that decides T1–T6's shape: **a template with blanks cannot be checked,
    because it is not yet the thing the check checks.** Every law test below would pass
    against a file full of `{{...}}` while asserting nothing, so this test guards the
    precondition the others depend on.
    """
    for value in value_positions(PAYMENTS.policies_path.read_text(encoding="utf-8")):
        for marker in PLACEHOLDERS:
            assert marker not in value, f"the pack carries a placeholder: {value.strip()!r}"


def test_every_effect_the_pack_names_is_declared(fresh: Connection) -> None:
    """Q3's law, asserted by `coverage.build` rather than by a checker written here."""
    PAYMENTS.adopt(fresh, ratified_by_session="tests", now=FROZEN_NOW)
    inert = [r for r in coverage.build(fresh).effects if r.state == coverage.DECLARED_INERT]
    assert inert == [], (
        f"the pack labels effects nothing declares: {[r.name for r in inert]} — each is a "
        "silent permit, a protection that depends on a second, optional declaration"
    )


def test_no_declared_effect_has_a_null_floor() -> None:
    """The `ND-040`/U4 half of the same law family.

    A null `min_tier` beside an opaque-host block is how an opaque destination
    auto-executed once before: the protection depended on the floor also being declared.
    """
    _, effects = PAYMENTS.load()
    assert effects, "the pack declares no effects at all"
    nulls = [e.effect for e in effects if e.min_tier is None]
    assert nulls == [], f"declared with no floor, so the label is decorative: {nulls}"


def test_every_effect_a_url_rule_adds_is_declared_with_a_floor() -> None:
    """The U4 shape precisely: opaque matching whose safety needs a second declaration."""
    policies, effects = PAYMENTS.load()
    floors = {e.effect: e.min_tier for e in effects}
    for policy in policies:
        for rule in policy.param_effects:
            if rule.url is None:
                continue
            for effect in rule.add_effects:
                assert effect in floors, (
                    f"{policy.action_type}'s url rule adds {effect!r}, which nothing declares"
                )
                assert floors[effect] is not None, (
                    f"{policy.action_type}'s url rule adds {effect!r}, declared with a null "
                    "floor — an opaque host would auto-execute"
                )


def test_the_engines_own_validator_accepts_every_rule() -> None:
    """`validate_policy` is the checker; this reads its answer rather than repeating it."""
    policies, _ = PAYMENTS.load()
    for policy in policies:
        policy_loader.validate_policy(policy)


def test_every_auto_executing_rule_declares_a_reversal() -> None:
    """Invariant 10, restated where a pack author will trip over it."""
    policies, _ = PAYMENTS.load()
    for policy in policies:
        if policy.tier in (Tier.AUTO, Tier.AUTO_CAPPED):
            assert policy.compensating_command, f"{policy.action_type} auto-executes with no undo"


def test_the_coverage_map_of_the_adopted_pack_is_clean_where_it_should_be(
    adopted: Connection,
) -> None:
    """Adopted with no traffic: nothing inert, nothing uncovered, effects unreached."""
    m = coverage.build(adopted)
    tally = m.counts(m.effects)
    assert tally[coverage.DECLARED_INERT] == 0
    assert m.counts(m.actions)[coverage.UNCOVERED_OBSERVED] == 0
    assert tally[coverage.UNREACHED] == len(m.effects), (
        "with no traffic every declared effect is UNREACHED — absent, not safe"
    )


# --- T5: behaviour, with asserted verdicts ------------------------------------------


def test_a_small_transfer_is_permitted_and_capped(
    adopted: Connection, config: EngineConfig
) -> None:
    verdict, tier = _verdict(
        _decide(
            adopted,
            config,
            "payments.transfer",
            {"amount_eur": Decimal("120.00"), "destination_account": "acct-1"},
            "120.00",
        )
    )
    assert (verdict, tier) == ("permitted", int(Tier.AUTO_CAPPED))


def test_a_transfer_over_the_daily_cap_is_denied(adopted: Connection, config: EngineConfig) -> None:
    """The cap is the control, and it is asserted as a DENIAL rather than as "no error"."""
    _decide(
        adopted,
        config,
        "payments.transfer",
        {"amount_eur": Decimal("400.00"), "destination_account": "a"},
        "400.00",
    )
    outcome = _decide(
        adopted,
        config,
        "payments.transfer",
        {"amount_eur": Decimal("400.00"), "destination_account": "b"},
        "400.00",
    )
    verdict, _ = _verdict(outcome)
    assert verdict == "denied"
    assert outcome.decision.reason_code.value in {"cap_value", "cap_rate"}


def test_a_transfer_over_the_declared_bound_is_denied_not_proposed(
    adopted: Connection, config: EngineConfig
) -> None:
    """Out of bounds is a denial: nobody is asked to approve an out-of-bounds action."""
    outcome = _decide(
        adopted,
        config,
        "payments.transfer",
        {"amount_eur": Decimal("5000.00"), "destination_account": "a"},
        "5000.00",
    )
    verdict, _ = _verdict(outcome)
    assert verdict == "denied"
    assert outcome.decision.reason_code.value == "bounds"


def test_a_transfer_missing_its_amount_is_denied(adopted: Connection, config: EngineConfig) -> None:
    """An absent amount is not a zero amount — the cap would otherwise pass for free."""
    outcome = _decide(adopted, config, "payments.transfer", {"destination_account": "a"})
    assert _verdict(outcome)[0] == "denied"


def test_a_batch_payout_always_goes_to_a_human(adopted: Connection, config: EngineConfig) -> None:
    verdict, tier = _verdict(_decide(adopted, config, "payouts.schedule", {"batch_id": "b-1"}))
    assert (verdict, tier) == ("proposed", int(Tier.CONFIRM))


def test_a_ledger_read_is_observed_and_never_executed(
    adopted: Connection, config: EngineConfig
) -> None:
    verdict, tier = _verdict(_decide(adopted, config, "ledger.read", {"account_id": "a-1"}))
    assert tier == int(Tier.OBSERVE)
    assert verdict != "permitted", "an observe-tier action is recorded, never executed"


def test_a_webhook_to_the_named_partner_goes_to_a_human(
    adopted: Connection, config: EngineConfig
) -> None:
    """`hosts` names the SENSITIVE destinations; the effect applies when the target matches.

    The first draft of this pack had the rule backwards, as an allowlist — *anything not
    on this list is suspect* — and these tests are what caught it. The engine has no rule
    shape meaning that, and the pack no longer implies one.
    """
    verdict, tier = _verdict(
        _decide(
            adopted,
            config,
            "webhooks.post",
            {"url": "https://api.partner.example/hooks/1", "payload_id": "p-1"},
        )
    )
    assert (verdict, tier) == ("proposed", int(Tier.CONFIRM))


def test_a_shortened_url_that_might_be_the_partner_gets_the_same_floor(
    adopted: Connection, config: EngineConfig
) -> None:
    """`ND-040`/U4, demonstrated: **you cannot dodge the control with a shortener.**

    `https://t.co/x9k2` canonicalizes perfectly and genuinely IS `t.co`, so it does not
    match the declared host — but its real target is unknowable without a network call
    the PDP will not make. A member of the declared opaque class is therefore treated as
    though it WERE the declared target, and the floor decides.

    This is the assertion that fails under the U4 defect: with a null floor on
    `net.egress` the same request auto-executes.
    """
    verdict, tier = _verdict(
        _decide(adopted, config, "webhooks.post", {"url": "https://t.co/x9k2", "payload_id": "p-1"})
    )
    assert (verdict, tier) == ("proposed", int(Tier.CONFIRM))


def test_an_ordinary_webhook_runs_at_the_rules_own_tier(
    adopted: Connection, config: EngineConfig
) -> None:
    """The rule does not fire for an unrelated host, and the pack says so out loud."""
    verdict, tier = _verdict(
        _decide(
            adopted,
            config,
            "webhooks.post",
            {"url": "https://status.example.com/ping", "payload_id": "p-1"},
        )
    )
    assert (verdict, tier) == ("permitted", int(Tier.AUTO_CAPPED))


def test_an_undeclared_action_is_refused_by_default_deny(
    adopted: Connection, config: EngineConfig
) -> None:
    """The pack does not silently widen the world it governs."""
    outcome = _decide(adopted, config, "payments.wire_anywhere", {"amount_eur": Decimal("1")})
    verdict, tier = _verdict(outcome)
    assert (verdict, tier) == ("proposed", int(Tier.CONFIRM))
    assert outcome.decision.reason_code.value == "default_deny"


# --- T6 + adoption ------------------------------------------------------------------


def test_adoption_goes_through_the_ceremony_and_the_receipt_cites_the_pack(
    fresh: Connection,
) -> None:
    """R051 §6: `candidate_digest` IS the pack's `policy_digest`, by construction.

    So pack lineage is recoverable by **recomputation** — anyone holding the pack can
    compute that value and match it against the receipt — rather than by a stored
    pointer, which is this product's method applied to its own supply chain.
    """
    receipt = PAYMENTS.adopt(fresh, ratified_by_session="operator-1", now=FROZEN_NOW)
    assert receipt.candidate_digest == PAYMENTS.policy_digest()
    assert receipt.from_version is None, "a fresh store has no previous version"
    assert receipt.to_version == policy_loader.current_version(fresh)
    assert ratify.load(fresh, receipt.digest()) is not None, "the receipt must be sealed"


def test_adoption_without_a_backtest_is_allowed_and_visible(fresh: Connection) -> None:
    """A fresh store has nothing to replay, and the absence is present-and-null."""
    sealed = PAYMENTS.adopt(fresh, ratified_by_session="operator-1", now=FROZEN_NOW).sealed()
    assert "backtest_digest" in sealed and sealed["backtest_digest"] is None


def test_the_boundary_statement_names_the_absent_domains_rather_than_disclaiming() -> None:
    """*A named gap is a service to the reader; a disclaimer is a service to the writer.*"""
    text = PAYMENTS.boundary_path.read_text(encoding="utf-8").lower()
    for domain in (
        "sanctions screening",
        "kyc",
        "chargeback",
        "multi-currency settlement",
        "regulatory reporting",
    ):
        assert domain in text, f"the boundary statement does not name {domain!r}"
    assert "not a compliance artifact" in text


def test_the_pack_never_calls_itself_compliant_or_ready() -> None:
    """Keep the domain label; drop the compliance word. *"Worked examples: payments"* is honest."""
    for path in (PAYMENTS.boundary_path, PAYMENTS.policies_path):
        text = path.read_text(encoding="utf-8").lower()
        assert "worked examples" in text
        for claim in ("compliance-ready", "production-ready", "compliant with", "controls for"):
            assert claim not in text, f"{path.name} claims {claim!r}"
