"""`python -m onedoor.viewer` — generate the receipt page from a store (ND-051).

Read-only against a real store. The only writing this module does is `--demo-store`,
which builds a **labelled** sample store by running real decisions through the real
engine — never by writing rows into the audit table by hand. A demo whose receipts
were hand-written would be a demo of nothing, and every check the page runs would be
checking the demo author's arithmetic rather than the engine's.

Spec §3's fence in one line: static HTML, opened from disk, no backend, no network at
view time, no dashboards and no filters. The flags below are the whole surface.
"""

from __future__ import annotations

import argparse
import sys
from decimal import Decimal
from pathlib import Path
from uuid import uuid4
from zoneinfo import ZoneInfo

from onedoor.store.db import Database, tx
from onedoor.viewer.page import SAMPLE_MARKER_KEY, build_page

DEFAULT_OUT = Path("oneview-onedoor.html")


def seed_demo_store(path: Path) -> None:
    """Build a labelled sample store by driving the real engine.

    The label is written INTO the store, so a page generated from it is labelled no
    matter how the generator is invoked later. A flag on a command line is forgotten;
    a row in the artifact travels with it.
    """
    from onedoor.guardrail import policy_loader
    from onedoor.guardrail.decision import decide_and_reserve
    from onedoor.guardrail.executor import EngineConfig
    from onedoor.guardrail.models import (
        ActionRequest,
        Bounds,
        Caps,
        EffectPolicy,
        OpaqueHosts,
        ParamEffectRule,
        Policy,
        Source,
        Tier,
        UrlMatch,
    )
    from onedoor.store.clock import now_utc, to_iso

    database = Database(str(path))
    database.init()
    conn = database.connect()
    try:
        with tx(conn):
            conn.execute(
                "INSERT INTO config (key, value, updated_at) VALUES (?,?,?) "
                "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
                (
                    SAMPLE_MARKER_KEY,
                    "generated by `python -m onedoor.viewer --demo-store`",
                    to_iso(now_utc()),
                ),
            )
        policy_loader.upsert_effect(
            conn, EffectPolicy(effect="money.egress", min_tier=None, caps=Caps())
        )
        policy_loader.upsert_effect(
            conn, EffectPolicy(effect="net.unverified", min_tier=Tier.CONFIRM, caps=Caps())
        )
        policy_loader.upsert(
            conn,
            Policy(
                action_type="payments.transfer",
                tier=Tier.AUTO_CAPPED,
                dry_run=False,
                compensating_command="payments.reverse",
                caps=Caps(eur_day=Decimal("10")),
                cost_param="amount_eur",
                effects=["money.egress"],
                bounds=Bounds(strict_params=False, required=["amount_eur"]),
            ),
        )
        for name in ("payments.reverse", "crm.update_record", "docs.read"):
            policy_loader.upsert(
                conn,
                Policy(
                    action_type=name,
                    tier=Tier.AUTO,
                    dry_run=False,
                    compensating_command="payments.reverse",
                    bounds=Bounds(strict_params=False),
                ),
            )
        policy_loader.upsert(
            conn,
            Policy(
                action_type="net.http",
                tier=Tier.AUTO,
                dry_run=False,
                compensating_command="payments.reverse",
                bounds=Bounds(strict_params=False),
                param_effects=[
                    ParamEffectRule(
                        param="url",
                        add_effects=["net.unverified"],
                        url=UrlMatch(
                            hosts=["bank.example.com"],
                            schemes=["https"],
                            opaque=OpaqueHosts(),
                        ),
                    )
                ],
            ),
        )

        config = EngineConfig(
            approval_ttl_seconds=3600, connector_timeout_seconds=5.0, tz=ZoneInfo("UTC")
        )

        def ask(action: str, params: dict[str, object], cost: str = "0") -> None:
            now = now_utc()
            decide_and_reserve(
                ActionRequest(
                    request_id=uuid4(),
                    action_type=action,
                    params=params,  # type: ignore[arg-type]
                    source=Source.LLM,
                    rationale="oneview sample",
                    cost_eur=Decimal(cost),
                    created_at=now,
                ),
                conn=conn,
                config=config,
                now=now,
            )

        ask("docs.read", {"path": "README"})
        ask("crm.update_record", {"id": "c-1", "field": "notes"})
        ask("net.http", {"url": "https://t.co/x9k2", "method": "POST"})
        ask("payments.transfer", {"amount_eur": Decimal("4")}, cost="4")
        # The hero: over the daily cap, so it denies carrying a seven-field budget.
        ask("payments.transfer", {"amount_eur": Decimal("9")}, cost="9")
    finally:
        conn.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m onedoor.viewer",
        description="Generate the onedoor receipt page from an audit store. Read-only.",
    )
    parser.add_argument("--store", type=Path, help="path to the onedoor SQLite store")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="HTML file to write")
    parser.add_argument(
        "--demo-store",
        type=Path,
        help="build a LABELLED sample store at this path by running the real engine, "
        "then render it. The label is written into the store, not the command line.",
    )
    args = parser.parse_args(argv)

    if args.demo_store is None and args.store is None:
        parser.error("one of --store or --demo-store is required")
    if args.demo_store is not None and args.store is not None:
        parser.error("--store and --demo-store are mutually exclusive")

    store = args.demo_store if args.demo_store is not None else args.store
    if args.demo_store is not None:
        if store.exists():
            parser.error(f"{store} already exists; the demo store is built fresh, never merged")
        seed_demo_store(store)
    elif not store.is_file():
        parser.error(f"no store at {store}")

    database = Database(str(store))
    conn = database.connect()
    try:
        html = build_page(conn)
    finally:
        conn.close()
    args.out.write_text(html, encoding="utf-8")
    print(f"wrote {args.out} ({len(html.encode('utf-8'))} bytes) from {store}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
