"""The oneview design tokens, vendored from the spec (ND-051 / V2).

The token block below is **read from the spec file at import time**, not retyped.
That is X-11 applied to a design system: a colour transcribed by hand is a colour
that will differ from the other two skins by one digit, and the difference will be
invisible until three screenshots are put side by side in a launch deck.

`SPEC_FENCE_DIGEST` pins what was vendored — the `rederivable-manifest` pattern. If
core revises the spec, the digest stops matching, `tests/viewer/test_tokens.py` fails,
and someone has to look at what changed rather than absorbing it silently. A design
system that drifts quietly is the same failure mode as an instrument that drifts
quietly.

Two rules from spec §4 are enforced rather than remembered, in
`tests/viewer/test_tokens.py`:

- **semantic green/red never doubles as brand accent**, and
- **seal gold never signals state.**

They are one rule from two directions: the reader must be able to tell "this is ours"
from "this is the verdict" without reading the label. A page that says DENY in the
same gold as the wordmark has thrown away the one signal that matters.
"""

from __future__ import annotations

import hashlib
import re
from functools import lru_cache
from pathlib import Path

SPEC_PATH = Path(__file__).parent / "_vendor" / "ONEVIEW_DESIGN_SPEC.md"
"""Core's spec, vendored INTO the package rather than read from `docs/`.

`docs/oneview/` is where core delivers it, and a repo directory does not travel in a
wheel: an installed `onedoor` would find no spec and the viewer would be unusable
outside a checkout. So the spec ships in the package, `.gitattributes` fences both
copies as received data, and `test_the_vendored_spec_is_byte_identical_to_the_delivery`
proves the two are the same bytes rather than two similar files.
"""

SPEC_DIGEST = "72b428004c28c6fdc42257264a4aa7b834d4e12ca22fed9c3d78dbbd5f8e96b0"
"""sha256 of the whole vendored spec file. Generated by tooling, never typed (X-11)."""

SPEC_FENCE_DIGEST = "c066604cf754a4f88407f4a0ba64b8b5b385fd02519e6e4ab930e72cb0744c27"
"""sha256 of the spec's §4 CSS fence contents, generated by tooling and never typed."""

_FENCE = re.compile(r"```css\n(.*?)```", re.S)
_DECL = re.compile(r"(--[a-z-]+)\s*:\s*(#[0-9A-Fa-f]{6})")

# Declared beyond the token palette, each with the reason it is not a token.
ALLOWED_NON_TOKEN_COLOURS = {
    "#8a6f3d": "seal-dim: the reference mockup's dimmed seal, used only for rules and hairlines",
}


class TokenError(RuntimeError):
    """The spec could not be read, or does not carry what was vendored from it."""


@lru_cache(maxsize=1)
def css_block() -> str:
    """The spec's §4 fence, verbatim, with its digest checked.

    Raises rather than falling back to a bundled copy. A viewer that silently uses
    last week's palette when it cannot find the spec is a viewer that will be shipped
    with last week's palette.
    """
    if not SPEC_PATH.is_file():
        raise TokenError(f"the design spec is not where the viewer expects it: {SPEC_PATH}")
    match = _FENCE.search(SPEC_PATH.read_text(encoding="utf-8"))
    if match is None:
        raise TokenError("the design spec has no ```css fence; §4 is the token authority")
    block = match.group(1)
    digest = hashlib.sha256(block.encode("utf-8")).hexdigest()
    if digest != SPEC_FENCE_DIGEST:
        raise TokenError(
            f"the spec's token block has changed: it hashes to {digest[:12]}… and this "
            f"build pinned {SPEC_FENCE_DIGEST[:12]}…. Re-vendor deliberately; do not "
            f"absorb a design change without looking at it."
        )
    return block


@lru_cache(maxsize=1)
def palette() -> dict[str, str]:
    """`{token name: #rrggbb}` parsed from the vendored block."""
    return {name: value.lower() for name, value in _DECL.findall(css_block())}


def hex_values() -> frozenset[str]:
    """Every colour the design system declares, lowercased for comparison."""
    return frozenset(palette().values()) | frozenset(ALLOWED_NON_TOKEN_COLOURS)


def root_css() -> str:
    """The `:root` rule for the emitted page.

    The vendored block carries the two font lines in prose form (`font-sans: 'Archivo'
    (400/500/600/700), fallback system sans`), which is a spec sentence rather than
    CSS, so the custom properties are declared here and the *stacks* they name are the
    spec's. The colours come through untouched.
    """
    declarations = "\n  ".join(
        line.strip() for line in css_block().splitlines() if line.strip().startswith("--")
    )
    return (
        ":root{\n  "
        + declarations
        + "\n  --seal-dim:#8a6f3d;"
        + "\n  --mono:'IBM Plex Mono',ui-monospace,SFMono-Regular,Menlo,monospace;"
        + "\n  --sans:'Archivo',-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
        + "\n}"
    )
