"""The Policy Studio v2 design tokens — "the ledger room".

Read from a **vendored, digest-pinned block** at import time, never retyped. Same
pattern as `onedoor.viewer.tokens`, and the same X-11 reason: a colour transcribed by
hand differs from its source by one digit, and the difference is invisible until two
screens are put side by side.

## Why this is not `viewer.tokens`

The Studio does not share the oneview palette, and the divergence is **specified, not
drift**. The design note core named as binding authority (§3) says it in words:

> Ground: warm charcoal/umber (#1c1713 family), never blue-black.

oneview's ground is `#0b0d10` — blue-black, on purpose, for a document meant to read as
a printed record. The Studio is a room you work in. The note also settles the reach of
the shared spec: *"Studio is an editor, not a oneview viewer — §3 static fence does not
apply, but §4 (seal never state) binds everywhere."* So the **rule** travels and the
**palette** does not, which is why there are two token modules and one law.

The palette also carries a state colour oneview has no name for: `--review`. oneview
renders verdicts that have already happened, where a decision is allowed or refused;
the Studio renders policy, where *requires approval* is a first-class outcome. A third
state needed a third colour, and inventing one locally is exactly what this module
exists to prevent.

## The adjacency this module has to be honest about

`--gold` (`#c9a227`) is brand. `--review` (`#d07f3c`) is state. They are the two
warmest things on the page and they are **not** the same colour — measured, not
asserted, by `tests/studio/test_tokens.py`, which puts a floor under their separation
in hue and lightness. §4's rule is that gold never signals state; a review-amber a
reader could mistake for the wordmark would break that rule from the other side,
without a single line of CSS being wrong.
"""

from __future__ import annotations

import hashlib
import re
from functools import lru_cache
from pathlib import Path

BLOCK_PATH = Path(__file__).parent / "_vendor" / "LEDGER_ROOM_TOKENS.css"
"""The `:root` block, extracted verbatim from the approved mockup.

Vendored INTO the package rather than read from a doc directory, for the reason
`viewer.tokens` learned: a repo directory does not travel in a wheel, and an installed
Studio that cannot find its palette is an installed Studio that cannot render.
"""

BLOCK_DIGEST = "7a3a19a3f2505c7fe74695c7a38943c6edbb294d774c573d478353b03120a3e9"
"""sha256 of the vendored block. Generated by tooling, never typed (X-11)."""

SOURCE = "https://claude.ai/code/artifact/ee38c587-7761-4773-881a-764d21c0abdc"
"""The mockup R055 §0 names as binding design authority, approved 2026-08-28."""

_DECL = re.compile(r"(--[a-z0-9-]+)\s*:\s*([^;]+);")
_HEX = re.compile(r"^#[0-9a-f]{6}$")

#: Core's own artifact carried a measured defect, so the fix is recorded HERE rather
#: than edited INTO the vendored block. The block stays byte-identical to the mockup and
#: keeps its digest; the corrections are generated data beside it, each with the
#: measurement that forced it and the ruling that approved it.
#:
#: E10's two-discipline, arriving at a design system: **received bytes are never
#: rewritten, and a correction to received data is a new artifact that cites it.**
#: Editing the block would have been quicker and would have destroyed the one thing that
#: makes the palette auditable -- that it can still be compared to what core approved.
#:
#: R057 §5: *"the mockup is design authority for direction and anatomy, never for a
#: failing measurement. Accessibility is not a deviation from the design;
#: inaccessibility is."*
CORRECTIONS = {
    "--allow": ("#53a670", "4.18:1 on --allow-bg; WCAG AA needs 4.5:1 at chip size"),
    "--review": ("#d18240", "4.45:1 on --review-bg; WCAG AA needs 4.5:1 at chip size"),
    "--refuse": (
        "#cc766b",
        "3.33:1 on --refuse-bg -- the worst of the three, and the "
        "verdict a reader most needs to see",
    ),
}
"""`{token: (corrected value, the measurement that forced it)}` — R057 §5.

Hue and saturation are held; only lightness moves, and only as far as 4.55:1 (a hair
over the 4.5:1 requirement, so a rounding difference in any checker cannot flip a
passing build). Backgrounds and brand tokens are untouched.
"""

STATE_TOKENS = ("--allow", "--review", "--refuse")
"""The semantic triple. These three, and only these three, may carry a verdict."""

BRAND_TOKENS = ("--gold", "--gold-dim")
"""Brand. §4: seal gold never signals state — these never touch a verdict."""


class TokenError(RuntimeError):
    """The token block is missing, malformed, or not what was vendored."""


@lru_cache(maxsize=1)
def css_block() -> str:
    """The vendored `:root` block, verbatim, with its digest checked.

    Raises rather than falling back to a bundled default. A Studio that silently
    renders in last week's palette when it cannot find this file is a Studio that will
    be shipped in last week's palette.
    """
    if not BLOCK_PATH.is_file():
        raise TokenError(
            f"the Studio token block is not where it is expected: {BLOCK_PATH}. It ships "
            f"as package data; a wheel without it cannot render the Studio."
        )
    block = BLOCK_PATH.read_text(encoding="utf-8")
    digest = hashlib.sha256(block.encode("utf-8")).hexdigest()
    if digest != BLOCK_DIGEST:
        raise TokenError(
            f"the Studio token block has changed: it hashes to {digest[:12]}… and this "
            f"build pinned {BLOCK_DIGEST[:12]}…. Re-vendor from {SOURCE} deliberately; "
            f"do not absorb a design change without looking at it."
        )
    return block


@lru_cache(maxsize=1)
def mockup_declarations() -> dict[str, str]:
    """`{token: value}` exactly as the approved mockup declares them, uncorrected.

    Kept reachable so the corrections can be *diffed against their source* rather than
    merely asserted. A correction nobody can compare to what it corrected is a value
    with a story attached, not a provenance.
    """
    return {name: value.strip() for name, value in _DECL.findall(css_block())}


@lru_cache(maxsize=1)
def declarations() -> dict[str, str]:
    """The palette the Studio actually renders: the mockup's, with R057 §5 applied."""
    values = dict(mockup_declarations())
    for token, (corrected, _why) in CORRECTIONS.items():
        assert token in values, f"correcting {token}, which the mockup does not declare"
        values[token] = corrected
    return values


def palette() -> dict[str, str]:
    """Only the colour tokens, lowercased for comparison."""
    return {k: v.lower() for k, v in declarations().items() if _HEX.match(v.strip().lower())}


def hex_values() -> frozenset[str]:
    """Every colour the Studio is allowed to emit."""
    return frozenset(palette().values())


def root_css() -> str:
    """The `:root` rule for an emitted Studio page.

    The block is passed through with its declarations re-joined rather than reproduced
    as source text, so the emitted CSS is generated from the parsed tokens and a stray
    character in the vendored file cannot become a stray character in the page.
    """
    body = "".join(f"{name}:{value};" for name, value in declarations().items())
    return ":root{" + body + "}"
